{ "display_name":"Azure Functions",
  "description": "SignalFx's integration with Azure Functions.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/azure-functions",
  "code": "https://azure.microsoft.com/en-us/services/functions/",
  "featured": false,
  "logo_large": "integration_azurefunctions@2x.png",
  "logo_small": "intregration_azurefunctions.png",
  "data_signature": "is_Azure_Function:\"true\"",
  "in_app_categories": ["AzureServicesMonitored"]
}
